<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Vector Representations
## *Data Science Unit 4 Sprint 2 Assignment 2*

In [12]:
import re
import string

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import spacy

from bs4 import BeautifulSoup

## 1) *Clean:* Job Listings from indeed.com that contain the title "Data Scientist" 

You have `job_listings.csv` in the data folder for this module. The text data in the description column is still messy - full of html tags. Use the [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) library to clean up this column. You will need to read through the documentation to accomplish this task. 

In [62]:
from bs4 import BeautifulSoup
import requests

##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task.")
                


Exception: 
This task is not complete. 
Replace this line with your code for the task.

In [33]:
# from https://www.youtube.com/watch?v=87Gx3U0BDlo


# result = requests.get('https://..tatements/')
# src = result.content
# # soup = BeautifulSoup(src, 'lxml')
# soup = BeautifulSoup(src, 'html.parser')

# links = soup.find_all("a")

# # questions = soup.select(".question-summary")

# urls = []

# for h2_tag in soup.find_all("h2"):
#     a_tag = h2_tag.find('a')  
#      ## want the actual link
#     urls.append(a_tag.attrs['href'])
    
# # print(urls)

# for i in urls:
#     print(urls(i))

# len(urls)+2


In [67]:
indeed = pd.read_csv('./data/job_listings.csv')

print(indeed.shape)
indeed.head()

(426, 3)


Unnamed: 0                                        description  \
0           0  b"<div><div>Job Requirements:</div><ul><li><p>...   
1           1  b'<div>Job Description<br/>\n<br/>\n<p>As a Da...   
2           2  b'<div><p>As a Data Scientist you will be work...   
3           3  b'<div class="jobsearch-JobMetadataHeader icl-...   
4           4  b'<ul><li>Location: USA \xe2\x80\x93 multiple ...   

                          title  
0               Data scientist   
1              Data Scientist I  
2  Data Scientist - Entry Level  
3                Data Scientist  
4                Data Scientist

In [70]:
l1 = ['<.>', '<..>','<...>' ,'<...', '.>', "b'" , 'b"', '.+\n']

l2 = ['lass="jobsearch-JobMetadataHeader' ]

indeed['description'] = indeed['description'].str.replace('|'.join(l1)  , '', regex=True).str.strip()

In [71]:
indeed.head(10)

Unnamed: 0                                        description  \
0           0  Job Requirements:\nConceptual understanding in...   
1           1  Job Description\n\nAs a Data Scientist 1, you ...   
2           2  As a Data Scientist you will be working on con...   
3           3  c icl-u-xs-mb--md c-item n class="icl-u-xs-mr-...   
4           4  Location: USA \xe2\x80\x93 multiple locations\...   
5           5  Create various Business Intelligence Analytica...   
6           6  As Spotify Premium swells to over 96M subscrib...   
7           7  Everytown for Gun Safety, the nation's largest...   
8           8  MS in a quantitative discipline such as Statis...   
9           9  Slack is hiring experienced data scientists to...   

                                          title  
0                               Data scientist   
1                              Data Scientist I  
2                  Data Scientist - Entry Level  
3                                Data Scientist  
4                                Data Scientist  
5                                Data Scientist  
6  Associate Data Scientist – Premium Analytics  
7                                Data Scientist  
8                            Sr. Data Scientist  
9                      Data Scientist, Lifecyle

In [77]:
indeed['description'].value_counts()[:5]

About the Company\n\nCivis Analytics is a technology and strategic services company that works with organizations seeking to make more efficient, accurate, and data-driven decisions. Civis was founded in 2013 by former members of the analytics team on the 2012 Obama campaign and today works with some of the nation's leading progressive political and advocacy organizations, Fortune 500 companies, and major nonprofits.\n\nCivis' objective this year and next is simple: we want every political client organization to be data-driven and digital first. Here's how you'd help:\n\nFirst, the Civis platform is the technology of record for hundreds of in-house data scientists and analysts across the progressive movement. We seek to extend the feature set and capabilities to help these users quickly and self-reliantly accomplish their missions through data.\n\nSecond, Civis is building new digital technologies to help campaigns make the transition to digital outreach. It's 2019 after all. We're bui

## 2) Use Spacy to tokenize the listings 

In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

In [72]:
def tokenize(text):
    """Parses a string into a list of semantic units (words)

    Args:
        text (str): The string that the function will tokenize.

    Returns:
        list: tokens parsed out by the mechanics of your choice
    """
    
    tokens = re.sub('[^a-zA-Z 0-9]', '', text)
    tokens = tokens.lower().split()  
#     No need to put .lower   IF the DF is ALREADY in lowercase.
    
    return tokens

In [75]:
tokenize(str(indeed['description']))

['0',
 'job',
 'requirementsnconceptual',
 'understanding',
 'in1',
 'job',
 'descriptionnnas',
 'a',
 'data',
 'scientist',
 '1',
 'you',
 '2',
 'as',
 'a',
 'data',
 'scientist',
 'you',
 'will',
 'be',
 'working',
 'on',
 'con3',
 'c',
 'icluxsmbmd',
 'citem',
 'n',
 'classicluxsmr4',
 'location',
 'usa',
 'xe2x80x93',
 'multiple',
 'locations',
 '421',
 'about',
 'usnwant',
 'to',
 'be',
 'part',
 'of',
 'a',
 'fantastic',
 'and',
 '422',
 'c',
 'icluxsmbmd',
 'citem',
 'icluxsmtxsintern423',
 'c',
 'icluxsmbmd',
 'citem',
 'n',
 'classicluxsmr424',
 'senior',
 'data',
 'scientistnjob',
 'descriptionnnabou425',
 'cerner',
 'intelligence',
 'is',
 'a',
 'new',
 'innovative',
 'organname',
 'description',
 'length',
 '426',
 'dtype',
 'object']

In [78]:
indeed['tokens'] = indeed['description'].apply(tokenize)

In [79]:
# Tokenize description:

indeed['tokens']

0      [job, requirementsnconceptual, understanding, ...
1      [job, descriptionnnas, a, data, scientist, 1, ...
2      [as, a, data, scientist, you, will, be, workin...
3      [c, icluxsmbmd, citem, n, classicluxsmrxs4969,...
4      [location, usa, xe2x80x93, multiple, locations...
                             ...                        
421    [about, usnwant, to, be, part, of, a, fantasti...
422    [c, icluxsmbmd, citem, icluxsmtxsinternshipat,...
423    [c, icluxsmbmd, citem, n, classicluxsmrxs20000...
424    [senior, data, scientistnjob, descriptionnnabo...
425    [cerner, intelligence, is, a, new, innovative,...
Name: tokens, Length: 426, dtype: object

## 3) Use Scikit-Learn's CountVectorizer to get word counts for each listing.

In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [85]:
# create the transformer
vect = CountVectorizer()


# build vocab
vect.fit(indeed['description'])

# transform text
dtm = vect.transform(indeed['description'])


print(dtm)

  (0, 225)	1
  (0, 498)	1
  (0, 569)	2
  (0, 608)	2
  (0, 661)	1
  (0, 675)	1
  (0, 697)	1
  (0, 755)	1
  (0, 914)	1
  (0, 1071)	1
  (0, 1474)	1
  (0, 1530)	1
  (0, 1613)	1
  (0, 1690)	1
  (0, 2067)	1
  (0, 2128)	1
  (0, 2163)	1
  (0, 2478)	1
  (0, 2612)	1
  (0, 2844)	1
  (0, 2956)	2
  (0, 2973)	1
  (0, 3129)	1
  (0, 3156)	1
  (0, 3245)	1
  :	:
  (425, 9706)	1
  (425, 9742)	1
  (425, 9763)	1
  (425, 9811)	1
  (425, 9835)	2
  (425, 9872)	1
  (425, 9878)	1
  (425, 9880)	1
  (425, 9886)	2
  (425, 9899)	3
  (425, 9901)	1
  (425, 9915)	10
  (425, 9917)	2
  (425, 9918)	1
  (425, 9928)	6
  (425, 9934)	1
  (425, 9937)	1
  (425, 9940)	1
  (425, 9963)	5
  (425, 9976)	2
  (425, 10012)	3
  (425, 10080)	5
  (425, 10127)	2
  (425, 10134)	3
  (425, 10136)	1


In [86]:
print(vect.get_feature_names())

['00', '000', '02115', '03', '0356', '04', '062', '06366', '08', '10', '100', '1000', '1001', '1008', '100k', '100x', '105', '1079302', '1082692', '10b', '10ms', '10x', '11', '110k', '112', '114157802', '12', '120', '125', '126', '130', '1315', '1324b', '138', '14', '140', '15', '150', '15000', '159m', '16', '1605', '165', '169334br', '17', '170', '17b', '18', '180', '180008jq', '18b', '19', '190', '190007ji', '19000bn4', '19000c1k', '19004162', '1901744class', '1904', '1904labs', '1905', '19050', '1938', '1944', '1967', '1971', '1975', '1979', '1988', '199', '1994', '1999', '1b', '1st', '1strategy', '1tb', '20', '200', '2000', '200020183', '200041695', '2004', '2008', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2050', '21', '210', '2145', '2272', '24', '24m', '25', '250', '25256', '26', '260', '27', '28', '2nd', '2x', '30', '300', '30328', '30bn', '30k', '31', '317', '320', '3201', '33', '33051', '338', '35', '350', '3535', '35million', '36', '360'

In [97]:
indeed['tokens'][:25]

0     [job, requirementsnconceptual, understanding, ...
1     [job, descriptionnnas, a, data, scientist, 1, ...
2     [as, a, data, scientist, you, will, be, workin...
3     [c, icluxsmbmd, citem, n, classicluxsmrxs4969,...
4     [location, usa, xe2x80x93, multiple, locations...
5     [create, various, business, intelligence, anal...
6     [as, spotify, premium, swells, to, over, 96m, ...
7     [everytown, for, gun, safety, the, nations, la...
8     [ms, in, a, quantitative, discipline, such, as...
9     [slack, is, hiring, experienced, data, scienti...
10    [who, we, arenblackthorn, therapeutics, is, a,...
11    [c, icluxsmbmd, citem, icluxsmtxsparttimeclass...
12    [nfosysxe2x80x93, data, amp, analytics, xe2x80...
13    [as, spotify, premium, swells, to, over, 96m, ...
14    [experience, with, guiding, rampd, strategy, f...
15    [the, atlantic, is, seeking, a, data, scientis...
16    [the, challengeneventbrite, is, big, bustling,...
17    [c, icluxsmbmd, citem, icluxsmtxscontractw

In [98]:
dtm.todense()

AttributeError: 'DataFrame' object has no attribute 'todense'

### CountVectorizer with Spacy Processing

In [99]:

from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(stop_words='english', max_features=1000)

#Learn our Vocab
vect.fit(indeed['description'])

# Get sparse dtm
dtm = vect.transform(indeed['description'])

dtm = pd.DataFrame(dtm.todense(), columns=vect.get_feature_names())

In [100]:
dtm.head()

000  10  100  2019  40  abilities  ability  able  academic  access  ...  \
0    0   0    0     0   0          0        1     0         0       0  ...   
1    0   0    0     0   0          0        1     0         0       0  ...   
2    0   0    0     0   0          0        0     0         0       0  ...   
3    0   0    0     0   0          0        0     0         0       0  ...   
4    0   0    0     0   0          0        0     0         0       0  ...   

   xae  xb7  xbb  xc2  xe2  xef  xs  year  years  york  
0    0    0    0    1    0    0   0     0      0     0  
1    0    0    0    0    8    0   0     1      0     0  
2    0    0    0    0    0    0   0     0      0     0  
3    0    0    0    0    0    0   4     1      0     0  
4    0    0    0    0    1    0   0     0      1     0  

[5 rows x 1000 columns]

## 4) Visualize the most common word counts

In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

In [92]:
from collections import Counter

word_counts = Counter()
indeed['tokens'].apply(lambda x: word_counts.update(x))

word_counts.most_common(10)

[('and', 11541),
 ('to', 6803),
 ('the', 5259),
 ('of', 4553),
 ('data', 4032),
 ('in', 3526),
 ('a', 3454),
 ('with', 3054),
 ('for', 2029),
 ('or', 1749)]

## 5) Use Scikit-Learn's tfidf  Vectorizer to get a TF-IDF feature matrix

In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

In [101]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Instantiate vectorizer object
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)

# Create a vocabulary and get word counts per document
# Similiar to fit_predict
dtm = tfidf.fit_transform(indeed['description'])

# Print word counts

# Get feature names to use as dataframe column headers
dtm = pd.DataFrame(dtm.todense(), columns=tfidf.get_feature_names())

# View Feature Matrix as DataFrame
dtm.head()

000   04   10  100  1079302   11   12  125   14   15  ...  yes  yeti  york  \
0  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   0.0   0.0   
1  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   0.0   0.0   
2  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   0.0   0.0   
3  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   0.0   0.0   
4  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   0.0   0.0   

   young  yrs  zenreach  zero  zeus   zf  zillow  
0    0.0  0.0       0.0   0.0   0.0  0.0     0.0  
1    0.0  0.0       0.0   0.0   0.0  0.0     0.0  
2    0.0  0.0       0.0   0.0   0.0  0.0     0.0  
3    0.0  0.0       0.0   0.0   0.0  0.0     0.0  
4    0.0  0.0       0.0   0.0   0.0  0.0     0.0  

[5 rows x 5000 columns]

## 6) Create a NearestNeighbor Model. Write the description of your ideal datascience job and query your job listings. 

In [ ]:
##### Your Code Here #####
raise Exception("\nThis task is not complete. \nReplace this line with your code for the task."

In [119]:
my_job = ["""
Leverage data and business principles to create and drive large scale FB Data Center programs
Define and develop the program for metrics creation, data collection, modeling, and reporting the operational performance of Facebooks data centers
Work cross-functionally to define problem statements, collect data, build analytical models and make recommendations
Be a self-starter, motivated by a passion for developing the best possible solutions to problems
Identify and implement streamlined processes for data reporting (PowerBI) and communication
Use analytical models to identify insights that are used to drive key decisions across the organization
Routinely communicate metrics, trends and other key indicators to leadership
Provide leadership and mentorship to other members of the team
Lead and support various ad hoc projects, as needed, in support of Facebooks Data Center strategy
Build and maintain data driven optimization models, experiments, forecasting algorithms and capacity constraint models
Leverage tools like R, Tableau, PHP, Python, Hadoop & SQL to drive efficient analytics
"""]

In [120]:
from sklearn.neighbors import NearestNeighbors

# Fit on DTM
nn = NearestNeighbors(n_neighbors=5, algorithm='kd_tree')
nn.fit(dtm)

NearestNeighbors(algorithm='kd_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [121]:
nn.kneighbors([dtm.iloc[0].values])

(array([[0.        , 1.2818843 , 1.29245566, 1.2955652 , 1.30304622]]),
 array([[  0, 336, 276, 274, 366]], dtype=int64))

In [122]:
# Query my_job Using kneighbors 
nn.kneighbors([dtm.iloc[67]])

(array([[0.        , 1.25238548, 1.26323763, 1.26433063, 1.26433063]]),
 array([[ 67, 135, 200, 323, 141]], dtype=int64))

In [123]:
indeed['description'][30][:100]

'c icl-u-xs-mb--md c-item icl-u-xs-mt--xsInternshipOverview\\nEvery day at Perspecta, we enable hundre'

In [124]:
# Query for Sim of my_job
new = tfidf.transform(my_job)

In [125]:
new

<1x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 85 stored elements in Compressed Sparse Row format>

In [127]:
# indeed['description'][111]

## Stretch Goals

 - Try different visualizations for words and frequencies - what story do you want to tell with the data?
 - Scrape Job Listings for the job title "Data Analyst". How do these differ from Data Scientist Job Listings
 - Try and identify requirements for experience specific technologies that are asked for in the job listings. How are those distributed among the job listings?
 - Use a clustering algorithm to cluster documents by their most important terms. Do the clusters reveal any common themes?
  - **Hint:** K-means might not be the best algorithm for this. Do a little bit of research to see what might be good for this. Also, remember that algorithms that depend on Euclidean distance break down with high dimensional data.
 - Create a labeled dataset - which jobs will you apply for? Train a model to select the jobs you are most likely to apply for. :) 